name: Lint GitHub Actions files

on:
  pull_request:
    paths:
      - '.github/workflows/**'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1
        with:
          tool_name: actionlint
          reporter: github-pr-review
          fail_on_error: true
