name: Lint GitHub Actions files

on:
  pull_request:
    paths:
      - '.github/workflows/**'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: reviewdog/action-actionlint@e37e2ca68a70112d21e135229272da28ce2d0d5a # v1.66.1
        with:
          tool_name: actionlint
          reporter: github-pr-review
          fail_on_error: true
